import type { IconType } from "react-icons";
import {
  SiHtml5,
  SiCss3,
  SiJavascript,
  SiTypescript,
  SiReact,
  SiNextdotjs,
  SiNodedotjs,
  SiGit,
  SiRedux,
  SiExpress,
  SiSequelize,
  SiPostgresql,
  SiNestjs,
  SiMui,
  SiTailwindcss,
  SiBootstrap,
  SiWordpress,
  SiElementor,
  SiWoocommerce,
  SiMysql,
  SiMongodb,
} from "react-icons/si";
import { FaDatabase } from "react-icons/fa";
import { TbBrandFramerMotion } from "react-icons/tb";

export const skillIcons: Record<string, IconType> = {
  HTML: SiHtml5,
  CSS: SiCss3,
  JavaScript: SiJavascript,
  TypeScript: SiTypescript,
  React: SiReact,
  "Next.js": SiNextdotjs,
  "Node.js": SiNodedotjs,
  "Tailwind CSS": SiTailwindcss,
  Bootstrap: SiBootstrap,
  WordPress: SiWordpress,
  Elementor: SiElementor,
  WooCommerce: SiWoocommerce,
  Git: SiGit,
  Redux: SiRedux,
  Express: SiExpress,
  "Nest.js": SiNestjs,
  PostgreSQL: SiPostgresql,
  MySQL: SiMysql,
  MongoDB: SiMongodb,
  Sequelize: SiSequelize,
  TypeORM: FaDatabase,
  "Material UI": SiMui,
  "Framer Motion": TbBrandFramerMotion,
};
